Fixed loading issue for vocabs trained using seomoz/vocab
Loading a vocab trained using Moz's original vocab implementationresulted in:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d

Fixed problem by loading and writing vocabs explicitly with a utf-8 encoding since this seems to be what it was implicitly doing before anyway.